language: php

php:
  - 5.4

before_script:
  - composer install --prefer-dist

script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - bin/phpcs --standard=PSR2 src --ignore=vendor
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - dardarlt@gmail.com