dardarlt_twitter_task:
    resource: "@DardarltTwitterTaskBundle/Resources/config/routing.yml"
    prefix:   /task2

dardarlt_cookie_task:
    resource: "@DardarltCookieTaskBundle/Resources/config/routing.yml"
    prefix:   /task1
