

services:
    tt.twitter_connection:
        class: Dardarlt\Bundle\TwitterTaskBundle\Provider\TwitterConnection
        arguments: [%consumer_key%, %consumer_secret%]

    tt.twitter_call:
        class: Dardarlt\Bundle\TwitterTaskBundle\Provider\TwitterCallProvider
        arguments: [@tt.twitter_connection]