# app/config/services.yml
services:

    ct.cookie_factory:
        class: Dardarlt\Bundle\CookieTaskBundle\Factory\CookieFactory

    ct.parameter_listener:
        class: Dardarlt\Bundle\CookieTaskBundle\EventListener\ParameterListener
        arguments: [@ct.cookie_factory]
        tags:
             - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }